wingled22/pagyeonjaFrontEnd

src/App.jsx, src/assets/css/RiderPage.css, src/components/RiderProfile.jsx, src/components/RiderTable.jsx, src/routes/RiderPage.jsx
created design for rider dashboard
=> 3 rider ride history dashboard

src/assets/css/Charts.css, src/assets/css/NavigationBar.css, src/components/Homepage/Charts.jsx, src/components/Homepage/cards/CardItem.jsx
Adjusted the responsiveness of charts
=> 1 main dashboard design

src/assets/css/CommuterSuspensionModal.css, src/components/Commuter/CommuterAccordion.jsx, src/components/Commuter/CommuterDetails.jsx, src/components/Commuter/CommuterSuspensionModal.jsx, src/components/Commuter/CommuterTable.jsx
- added input for reason
- added date selection for termination of suspension
- disabled the past dates
=> added form modal for the suspension of the commuter

src/assets/css/CommuterTable.css, src/components/Commuter/CommuterDocumentViewerModal.jsx, src/components/Commuter/CommuterTable.jsx
=> 35 commuter document viewer modal

src/components/Commuter/CommuterTable.jsx, src/components/Commuter/CommuterUpdateModal.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/36
=> commuter update

src/assets/css/RiderSuspensionModal.css, src/components/Rider/RiderSuspensionModal.jsx, src/components/Rider/RiderTable.jsx
designed a rider suspension modal
=> created rider suspension modal design

src/assets/css/CommuterDocumentViewerModal.css, src/assets/css/CommuterTable.css, src/routes/CommuterPage.jsx
added conditional statement that if there is none selected commuter, the container of the detail will hide
=> 52 view image modal

src/assets/css/CommuterApproval/CommuterApprovalTablePage.css, src/assets/css/RiderApprovalDashboard.css, src/components/CommuterApproval/CommuterApprovalBadge.jsx, src/components/CommuterApproval/CommuterApprovalFilter.jsx, src/components/CommuterApproval/CommuterApprovalTablePage.jsx, src/components/NavigationBar.jsx, src/components/RiderApprovalComponents/Rider_Approval_Dashboard.jsx, src/components/RiderApprovalComponents/Rider_Approval_Table.jsx, src/routes/CommuterApprovalPage.jsx
Fixing some functionalities and add some conditional statement to dashboard
=> Commuterdashboard

src/assets/css/RiderPage.css, src/components/Rider/RiderTable.jsx
displayed the rider's data to rider table in rider dashboard
=> display the riders to rider table

src/components/Rider/RiderTable.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/82
=> saerching for rider approval dashboard

src/assets/css/RiderApproval/RiderApprovalDashboard.css, src/assets/css/RiderPage.css, src/components/RiderApproval/RiderApprovalSearchAndFilter.jsx, src/components/RiderApproval/Rider_Approval_Table.jsx, src/routes/CommuterApprovalPage.jsx, src/routes/RiderApprovalPage.jsx
Fixing Search And Filter Design from Rider Approval
=> fixing rider approval search and filter ui

src/components/CommuterApproval/CommuterApprovalSearchFilter.jsx, src/components/CommuterApproval/CommuterApprovalTablePage.jsx, src/components/RiderApproval/RiderApprovalSearchAndFilter.jsx
"Already made the search field functional."
=> "Already made the search field functional."

src/assets/css/RiderDetailsModal.css, src/assets/css/RiderPage.css, src/components/Rider/RiderDetailsModal.jsx, src/components/Rider/RiderTable.jsx
displayed details of rider in modal
=> 87 display rider details in modal

src/assets/css/RiderPage.css, src/components/Rider/RiderProfile.jsx
display rider profile image in rider dashboard
=> display profile picture for rider profile dashboard

src/assets/css/CommuterDetails.css, src/components/Commuter/CommuterDetails.jsx
displayed the profile picture for commuter dashboard
=> displayed the profile image for commuter dashboard

src/assets/css/CommuterDetails.css, src/components/Commuter/CommuterDetails.jsx
fixed nullable profile path 
an icon will display if there is no profile picture being uploaded in database
=> 107 fixed the nullable profile path image in commuter

src/assets/css/RiderPage.css, src/components/Commuter/CommuterDetails.jsx, src/components/Rider/RiderProfile.jsx
fixed the nullable profile path to display icon if there is no value in it
=> fixed the nullable profile path for displaying in rider dashboard

src/assets/css/RiderDetailsModal.css, src/assets/css/RiderPage.css, src/components/Commuter/CommuterDetails.jsx, src/components/Rider/RiderDetailsModal.jsx, src/components/Rider/RiderProfile.jsx, src/components/Rider/RiderTable.jsx, src/components/RiderApproval/Rider_Approval_Table.jsx
display the profile image in rider modal details and fixed nullable firstname and lastname in rider approval table
=> 114 display profile image to rider modal details

src/components/Commuter/CommuterDetails.jsx, src/components/Commuter/CommuterSuspensionModal.jsx, src/components/Commuter/CommuterTable.jsx
Done invoking suspension to the commuter
=> 112 suspend commuter

src/components/Rider/RiderTable.jsx, src/components/Rider/RiderUpdateModal.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/88
=> Update the selected rider information

src/components/Rider/RiderDetailsModal.jsx, src/components/Rider/RiderDocumentViewerModal.jsx, src/components/Rider/RiderProfile.jsx
fixed the image viewer
https://github.com/wingled22/pagyeonjaFrontEnd/issues/125
=> fixed the image viewer in rider document modal viewer

src/components/Rider/RiderDetailsModal.jsx, src/components/Rider/RiderProfile.jsx
fixed the rider the profile image not found in rider profile and rider modal
https://github.com/wingled22/pagyeonjaFrontEnd/issues/128
=> 128 UI fix rider image not found display default

src/components/Commuter/ViewImageModal.jsx, src/components/Rider/RiderDocumentViewerModal.jsx, src/components/RiderApproval/Requirements.jsx, src/components/RiderApproval/RequirementsCards.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/126
=> 126 rider  view requirement

src/components/Rider/RiderTable.jsx, src/components/Rider/RiderUpdateModal.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/133
=> fixing rider update

src/assets/css/RiderApproval/RiderApprovalDashboard.css, src/components/Commuter/CommuterDocumentViewerModal.jsx, src/components/Rider/RiderDocumentViewerModal.jsx, src/components/RiderApproval/Requirements.jsx, src/components/RiderApproval/RequirementsCards.jsx, src/components/RiderApproval/Rider_Approval_Table.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/123
=> 123 UI fixes images fix height and width

src/components/Rider/RiderSuspensionModal.jsx, src/components/Rider/RiderTable.jsx
=> created invoke suspension for rider

src/components/RiderApproval/RiderApprovalSearchAndFilter.jsx, src/components/RiderApproval/Rider_Approval_Table.jsx
Make Filter Status Functionable
=> Rider app filter

src/components/Commuter/CommuterDetails.jsx, src/components/Rider/RiderDetailsModal.jsx, src/components/Rider/RiderTable.jsx
display suspension status in redir detail modal
=> 147 display suspension status in rider details modal

src/components/Commuter/CommuterTable.jsx, src/components/Commuter/CommuterUpdateModal.jsx, src/components/Rider/RiderTable.jsx, src/components/Rider/RiderUpdateModal.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/127
=> 151 fix merge update rider

src/components/RiderApproval/ApprovalResponseConfirmationModal.jsx, src/components/RiderApproval/Requirements.jsx, src/components/RiderApproval/Rider_Approval_Table.jsx, src/routes/RiderApprovalPage.jsx, src/routes/RiderPage.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/141
=> 141 frontend approve or reject rider

package-lock.json, package.json, src/components/Rider/RiderUpdateModal.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/161
=> completed toaster update

src/components/RiderApproval/Rider_Approval_Table.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/168
=> 168 fix the approval page empty background

src/components/Rider/RiderDetailsModal.jsx
display documents in rider page
=> 160 viewing of documents in riders page

src/components/Commuter/CommuterDetails.jsx, src/components/Commuter/CommuterDocumentViewerModal.jsx
view documents in commuter dashboard
=> display documents in commuter document viewer modal

src/components/Rider/RiderProfile.jsx
fixed image load failed in rider profile
=> fixed image load failed in rider

src/components/Rider/RiderDetailsModal.jsx
fixed the rider profile image load in rider modal
=> fixed the rider profile image load in rider details modal

src/components/CommuterApproval/CommuterApprovalTablePage.jsx, src/components/Rider/RiderUpdateModal.jsx, src/routes/CommuterApprovalPage.jsx
removing some unwanted feature from rider update modal
=> removing some unwanted feature from rider update modal

src/components/RiderApproval/Requirements.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/190
=> Updated the api link for approval response in rider.

src/assets/css/CommuterApproval/CommuterApprovalTablePage.css, src/components/CommuterApproval/CommuterApprovalTablePage.jsx
fixing some bugs from commuter approval table
=> Taskmj#191

src/components/CommuterApproval/CommuterApprovalSearchFilter.jsx, src/components/CommuterApproval/CommuterApprovalTablePage.jsx
https://github.com/users/wingled22/projects/12/views/7?pane=issue&itemId=58486674
=> make the search commuter approval functional

src/components/Rider/RiderSuspensionModal.jsx, src/components/RiderApproval/ApprovalResponseConfirmationModal.jsx, src/components/RiderApproval/Requirements.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/198
=> Finished the rejection message for rider.

src/components/CommuterApproval/CommuterApprovalRequirements.jsx, src/components/CommuterApproval/CommuterApprovalRequirementsCards.jsx, src/components/CommuterApproval/CommuterApprovalTablePage.jsx, src/components/RiderApproval/Requirements.jsx, src/routes/CommuterApprovalPage.jsx
displayed the commuter details in commuter approval page
displayed the commuter documents in commuter approval page
=> display the commuter approval details and files in commuter approval page

src/assets/css/CommuterApproval/CommuterApprovalTablePage.css, src/components/CommuterApproval/CommuterApprovalTablePage.jsx
https://github.com/users/wingled22/projects/12/views/7?pane=issue&itemId=58491656
=> Taskmj#200

src/assets/css/CommuterSuspensionModal.css, src/assets/css/RiderDocumentViewerModal.css, src/components/CommuterApproval/CommuterApprovalRequirements.jsx, src/components/RiderApproval/ApprovalResponseConfirmationModal.jsx, src/components/RiderApproval/Requirements.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/208
=> 208 frontend rejection message for commuter approval

src/components/Rider/RiderTable.jsx, src/components/Rider/RiderUpdateModal.jsx, src/components/RiderApproval/Requirements.jsx, src/routes/RiderApprovalPage.jsx, src/routes/RiderPage.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/205
=> adding some toaster 

src/components/Rider/RiderDetailsModal.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/217
=> Addded some cleanup functions for the useEffects.

index.html
add text for enable the co authored
=> add text for enable the co authored

index.html
=> use for co author

src/components/Rider/RiderTable.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/223
=> Added some cleanup functions.

src/components/Rider/RiderProfile.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/227
=> Moved some state in the top level.

src/components/RiderApproval/Requirements.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/231
=> Fixing the  toaster

src/components/Rider/RiderTable.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/234
=> 234 frontend refactor the rider details 1

src/components/Rider/RiderTable.jsx, src/components/Rider/RiderUpdateModal.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/236
=> added a function for updating the current array without fetching the riders.

src/components/Rider/RiderTable.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/241
=> Modified the function for avoiding fetching riders in the db while updating the details/suspension status.

src/components/Rider/RiderTopUpModal.jsx
Succesfully Implemented correct type of data in top up history
=> 242 assign correct data into rider top up history

src/components/Commuter/CommuterAccordion.jsx, src/components/Commuter/CommuterDetails.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/237
=> done displaying

src/components/Rider/RiderTable.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/246
=> updated the revoke function for the rider to avoid fetching riders after revoke.

src/components/Rider/RiderDetailsModal.jsx, src/components/Rider/RiderTable.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/248
=> Fixed the cleanup function for the useEffects

package-lock.json, src/components/Commuter/CommuterTable.jsx, src/components/Commuter/CommuterUpdateModal.jsx, src/routes/CommuterPage.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/251
=> Avoid the fetching of commuters after update

src/components/Commuter/CommuterSuspensionModal.jsx, src/components/Commuter/CommuterTable.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/253
=> avoid the fetching of commuters while adding/revoking suspension.

src/components/CommuterApproval/CommuterApprovalRequirements.jsx, src/components/RiderApproval/Requirements.jsx, src/routes/CommuterApprovalPage.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/257
=> Add toater in commuter approval

src/components/Rider/RiderTable.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/259
=> Fixed the bug.

src/components/Rider/RiderTable.jsx, src/components/Rider/RiderTopUpModal.jsx
implementing real time data to the top up history accordion
=> Taskmj#249

src/components/Rider/RiderTopUpModal.jsx
=> fix accordion date and time

src/components/CommuterApproval/CommuterApprovalRequirements.jsx, src/components/CommuterApproval/CommuterApprovalTablePage.jsx, src/routes/CommuterApprovalPage.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/266
=> Avoided the fetching of commuter approvals while approving/rejecting commuter.

src/components/Rider/RiderTopUpModal.jsx
fixing undefined value from rider toptuphistory status accordion
=> fixing undefined value from rider toptuphistory status accordion

src/components/RiderApproval/Requirements.jsx, src/routes/RiderApprovalPage.jsx
https://github.com/wingled22/pagyeonjaFrontEnd/issues/275
=> Avoided fetching approvals after rejecting/approving rider

src/components/CommuterApproval/CommuterApprovalRequirements.jsx, src/components/RiderApproval/Requirements.jsx, src/routes/CommuterApprovalPage.jsx, src/routes/RiderApprovalPage.jsx, src/utils/commuter/approvedCommuterSlice.js, src/utils/commuterApproval/commuterApprovalSlice.js, src/utils/riderApproval/riderApprovalSlice.js, src/utils/riders/approvedRiderSlice.js
https://github.com/wingled22/pagyeonjaFrontEnd/issues/285
=> Fix null value errors
